uploads = []
generated = []

[[outputs]]
id = "NE4xTze33LH5gvVWc2Y5j"
uri = "file://exports/jenny-v2.zip"
type = "unspecified"
title = "jenny-v2.zip — fully updated"

[[outputs]]
id = "I_2218QE-lXHZ50t92X8T"
uri = "file://exports/jenny-v3.zip"
type = "unspecified"
title = "jenny-v3.zip — spooning sleep sex scene"

[[outputs]]
id = "EFQcOqoxKMfmp5L0P5u8B"
uri = "file://exports/jenny-v4.zip"
type = "unspecified"
title = "jenny-v4.zip — full release"
